name: women_safety_app
description: Women safety app demo
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # REST APIs
  http: ^1.1.0
  url_launcher: ^6.3.0

  
  

  # Save token locally
  shared_preferences: ^2.2.2
  google_maps_flutter: ^2.5.0

  # Get current GPS location
  geolocator: ^9.0.2

  # OpenStreetMap rendering
  flutter_map: ^6.2.1
  latlong2: ^0.9.0
  

  # UI & Material goodies
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

 

  
flutter:
  uses-material-design: true
  assets:
    # uncomment these ONLY if folders exist
    # - assets/icons/
    # - assets/audio/

    